name: bwc_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cloud_firestore: 3.1.10
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.19
  firebase_core: 1.17.1
  flutter:
    sdk: flutter
  get: 4.6.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
